PROMPT ===== RMAN Backup Status =====

COLUMN STATUS FORMAT A15
COLUMN INPUT_TYPE FORMAT A20

SELECT
    SESSION_KEY,
    INPUT_TYPE,
    STATUS,
    START_TIME,
    END_TIME,
    ROUND(OUTPUT_BYTES/1024/1024,2) AS SIZE_MB
FROM V$RMAN_BACKUP_JOB_DETAILS
ORDER BY START_TIME DESC;
